# Generated by Django 6.0.5 on 2026-06-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Land', 'Land')], default='House', max_length=20),
        ),
    ]
