# Generated by Django 6.0.5 on 2026-06-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_inquiry_user_property_latitude_property_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
